### ISSUE TITLE
Error responses should return a unique error code, different to the HTTP status code

### ISSUE THREAD

**Issue by craicoverflow** [bf2fc6cc711aee1a0c2a/kafka-admin-api#127]
The Kafka Admin API returns an HTTP status code, error message, and the error class as the main properties of the response payload when there is an error.

Clients consuming the API needs to be able to differentiate between different error types which are grouped under the same status code.

Example: when I try to reset the offset of a consumer group, I can get a `400 Bad Request` in various scenarios. The client will probably want to display a custom error message to the user, as sometimes the  response message is too technical for the user and for internationalisation purposes. Without the presence of a unique error code, I have no way to differentiate and appropriately handle this information in the client.

An example of an error response with this new payload format:

```json
{
   "code": 43982,
   "status":404,
   "error_message":"This server does not host this topic-partition.",
   "class":"UnknownTopicOrPartitionException"
}
```

To keep this backwards compatible, we could call the new error code `error_code` instead.

**Comment by MikeEdgar** [comment]
@wtrocki this will be included in the PR for [MGDSTRM-8218](https://issues.redhat.com/browse/MGDSTRM-8218) to improve alignment with the app services API guidelines.

**Comment by MikeEdgar** [comment]
@wtrocki , @craicoverflow what is the intended use of the error codes and `href` property in the standard `Error` object [1]? My concern as I am working through some refactoring is that this project has one big global error handler [2] where we have lost context of the error. If the error code should be unique for a specific occurrence of an error, I think some more robust error handling needs to be in place before this can be done properly.

[1] https://github.com/redhat-developer/app-services-api-guidelines/tree/main/spectral#rhoas-error-schema
[2] https://github.com/bf2fc6cc711aee1a0c2a/kafka-admin-api/blob/main/kafka-admin/src/main/java/org/bf2/admin/kafka/admin/handlers/CommonHandler.java#L57

**Comment by wtrocki** [comment]
@MikeEdgar we had the same problem for srs fleet manager. I believe that implemenation there can be reused. Jakub have been using APIError with code and  message. Any other error gets 500

**Comment by craicoverflow** [comment]
> what is the intended use of the error codes and href

This comes from the guidelines for api.openshift.com by App SRE. Those guidelines were created for the control plane service APIs for OpenShift and lots of it might not make sense to apply here or in other data plane APIs.
